/**
 * @file    tmc2209_port.h
 * @brief   Hardware port layer for TMC2209 on STM32 HAL.
 *
 * The "main.h" generated by CubeMX already includes the correct
 * stm32xxxx_hal.h for every family (F0/F1/F4/F7/G0/G4/H7/L4/U5...), so this
 * library does not depend on the chip family. The macros below can be
 * overridden before inclusion (e.g. in main.h).
 */
#ifndef TMC2209_PORT_H
#define TMC2209_PORT_H

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"

/* ---- Timing ---------------------------------------------------------------- */
#ifndef TMC_GET_TICK_MS
#define TMC_GET_TICK_MS()            HAL_GetTick()
#endif
#ifndef TMC_DELAY_MS
#define TMC_DELAY_MS(ms)             HAL_Delay(ms)
#endif

/* ---- Critical section (motion layer: main <-> timer ISR) ------------------ */
#ifndef TMC_CRITICAL_ENTER
#define TMC_CRITICAL_ENTER()         uint32_t _tmc_primask = __get_PRIMASK(); __disable_irq()
#endif
#ifndef TMC_CRITICAL_EXIT
#define TMC_CRITICAL_EXIT()          __set_PRIMASK(_tmc_primask)
#endif

/* ---- Fast GPIO access in ISR (BSRR available on current STM32 families) --- */
#ifndef TMC_PIN_HIGH
#define TMC_PIN_HIGH(port, pin)      ((port)->BSRR = (uint32_t)(pin))
#endif
#ifndef TMC_PIN_LOW
#define TMC_PIN_LOW(port, pin)       ((port)->BSRR = (uint32_t)(pin) << 16U)
#endif
#ifndef TMC_PIN_TOGGLE
#define TMC_PIN_TOGGLE(port, pin)    HAL_GPIO_TogglePin((port), (pin))
#endif

/* ---- UART bus defaults ----------------------------------------------------- */
#ifndef TMC_DEFAULT_TIMEOUT_MS
#define TMC_DEFAULT_TIMEOUT_MS       10U   /* 115200 baud: 12 bytes ~1.1 ms    */
#endif
#ifndef TMC_DEFAULT_RETRIES
#define TMC_DEFAULT_RETRIES          3U
#endif

#ifdef __cplusplus
}
#endif
#endif /* TMC2209_PORT_H */
